### ISSUE TITLE
Práctica, Operaciones aritméticas con sistemas numéricos 

### ISSUE THREAD

**Issue by Fidel20-01** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-Fidel20-01#1]
[PRACTICA 1 OPERACIONES ARITMETICAS CON SISTEMAS NUMERICOS.pdf](https://github.com/user-attachments/files/16841427/PRACTICA.1.OPERACIONES.ARITMETICAS.CON.SISTEMAS.NUMERICOS.pdf)

**Comment by josealfredo79** [comment]
Portada:22/25
Procedimiento:24/25
Figuras ilustraciones y fotografias :25/25
Resultados y conclusiones:24/25
Calificacion final:19
